server:
  port: 8087
  
spring:
  application:
    name: zuulproxyui
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp  
    
zuul:
  routes:
    customerservice:
      path: /rest/api/customers/**
      service-id: customerservice
      strip-prefix: false  
      
    customerservice1:
      path: /nonrest/api/customers/**
      service-id: customerservice
      strip-prefix: false
      
    customerserviceui:
       path: /ui/**
       service-id: customerui
       strip-prefix: false  
      
    catalog:
      path: /api/catalog/**
      service-id: catalog
      strip-prefix: false
      
    order:
      path: /api/orders/**
      service-id: order    
      strip-prefix: false
      
    hystrixframework:
      path: /api/hystrix/**
      service-id: mshystrix
      strip-prefix: false  
      
ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000      
          