server:
  port: 8098
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: CUSTOMERUI
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


zuul:
  routes:
    platformframework:
      path: /rest/api/customers/**
      service-id: customerservice
      strip-prefix: false
    
ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/