server:
  port: 8084
  
spring:
  application:
    name: mshystrix
    
api:
   zuul:
      url: http://localhost:8087    
      
feign:
  hystrix:
    enabled: true    
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/